spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
            temperature: 0.4
            max-tokens: 300
    retry:
      max-attempts: 2 # 원래 요청 1번 + 실패 시 재시도 1번 = 총 2번
      backoff:
        initial-interval: 500 # 실패 후 0.5초 대기 후 즉시 재시도
        multiplier: 1.5 # 재시도 대기 시간 1.5베 증가

cloud:
  aws:
    region: ${AWS_REGION}
    auth: iam
    s3:
      bucket: ${S3_BUCKET_NAME}
      base-url: ${CLOUD_FRONT_DOMAIN}

logging:
  level:
    root: warn

toss:
  secret-key: ${TOSS_SECRET_KEY}