spring:
  application:
    name: three-servings-api

  # local 환경 실행 기분
  profiles:
    default: local

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
            temperature: 0.4
            max-tokens: 300
    retry:
      max-attempts: 1 # 원래 요청 1번 + 실패 시 재시도 0번 = 총 1번

server:
  port: 19096

logging:
  level:
    root: info
  pattern:
    # %X{traceId:-} : MDC의 traceId, 없으면 빈칸 Spring Boot 표준 user추가 되면 이것도 중간에 넣기 ->  [%X{userId}]
    console: "%d{HH:mm:ss.SSS} [%X{traceId:-________}] %-5level %logger{15} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000     # 30분
  refresh-expiration: 1209600000 # 14일

cloud:
  aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
      base-url: ${CLOUD_FRONT_DOMAIN}